"use client";

import Link from "next/link";
import { Check, CircleStop, X } from "lucide-react";
import { useEffect, useState } from "react";

export default function RecordingClient() {
  const [seconds, setSeconds] = useState(0);
  const complete = seconds >= 120;
  useEffect(() => { const timer = window.setInterval(() => setSeconds((value) => Math.min(value + 1, 120)), 1000); return () => window.clearInterval(timer); }, []);
  const minutes = String(Math.floor(seconds / 60)).padStart(2, "0");
  const remaining = String(seconds % 60).padStart(2, "0");
  const progress = (seconds / 120) * 282.7;
  return <main className="flex min-h-screen flex-col items-center justify-center overflow-hidden px-5 py-16"><div className="w-full max-w-[720px] text-center"><h1 className="text-3xl font-bold leading-tight md:text-5xl">Should AI replace teachers?</h1><div className="relative mt-24 flex flex-col items-center"><div className="absolute -top-14 flex items-center gap-2 rounded-full border border-border bg-white px-4 py-2 text-xs font-bold uppercase tracking-wider text-muted-foreground shadow-sm"><span className={`size-3 rounded-full ${complete ? "bg-[#00885d]" : "bg-[#ef4444] animate-pulse-glow"}`}/>{complete ? "Minimum reached" : "Recording"}</div><div className="relative size-64"><svg className="size-full -rotate-90" viewBox="0 0 100 100"><circle cx="50" cy="50" r="45" fill="none" stroke="#e1e3e4" strokeWidth="4"/><circle className="progress-ring" cx="50" cy="50" r="45" fill="none" stroke={complete ? "#006c49" : "#4648d4"} strokeDasharray="282.7" strokeDashoffset={282.7 - progress} strokeLinecap="round" strokeWidth="4"/></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><span className={`font-mono text-5xl font-bold tabular-nums ${complete ? "text-[#006c49]" : ""}`}>{minutes}:{remaining}</span><span className="mt-2 max-w-[170px] text-center text-xs font-bold uppercase tracking-wider text-muted-foreground">{complete ? "Minimum reached. Keep going if you have more to say." : "Target: 2:00"}</span></div></div></div><div className="relative mt-20 flex w-full flex-col items-center gap-3"><p className={`absolute -top-12 rounded-lg bg-[#2e3132] px-4 py-2 text-xs text-white transition-opacity ${complete ? "opacity-0" : "opacity-80"}`}>Keep going, {Math.max(0, 120 - seconds)} seconds remaining.</p><button disabled={!complete} className="flex h-14 w-48 items-center justify-center gap-2 rounded-xl bg-[#e1e3e4] text-lg font-semibold text-muted-foreground transition enabled:bg-primary enabled:text-white enabled:shadow-lg"><Check size={20}/> Finish</button><Link href="/dashboard" className="flex h-12 w-48 items-center justify-center gap-2 rounded-xl border border-[#767586] text-sm font-semibold text-[#464554] transition hover:bg-[#edeeef]"><X size={18}/> Cancel</Link></div></div><div className="fixed bottom-6 right-6 hidden w-48 overflow-hidden rounded-xl border border-border bg-white p-3 shadow-lg md:block"><div className="flex aspect-[3/4] items-center justify-center rounded-lg bg-[#d9dff5] text-center text-xs font-semibold text-primary">Camera preview</div></div><CircleStop className="fixed left-6 top-6 text-muted-foreground" size={24}/></main>;
}
